-- GERADO por scripts/generate-seed.ts — NÃO editar à mão.
-- Fonte: openfootball/worldcup.json (2026). Reexecute com `pnpm seed:generate`.

truncate table public.palpites, public.partidas, public.selecoes cascade;

insert into public.selecoes (nome, codigo) values
  ('Algeria', 'ALG'),
  ('Argentina', 'ARG'),
  ('Australia', 'AUS'),
  ('Austria', 'AUT'),
  ('Belgium', 'BEL'),
  ('Bosnia & Herzegovina', 'BIH'),
  ('Brazil', 'BRA'),
  ('Canada', 'CAN'),
  ('Ivory Coast', 'CIV'),
  ('DR Congo', 'COD'),
  ('Colombia', 'COL'),
  ('Cape Verde', 'CPV'),
  ('Croatia', 'CRO'),
  ('Curaçao', 'CUW'),
  ('Czech Republic', 'CZE'),
  ('Ecuador', 'ECU'),
  ('Egypt', 'EGY'),
  ('England', 'ENG'),
  ('Spain', 'ESP'),
  ('France', 'FRA'),
  ('Germany', 'GER'),
  ('Ghana', 'GHA'),
  ('Haiti', 'HAI'),
  ('Iran', 'IRN'),
  ('Iraq', 'IRQ'),
  ('Jordan', 'JOR'),
  ('Japan', 'JPN'),
  ('South Korea', 'KOR'),
  ('Saudi Arabia', 'KSA'),
  ('Morocco', 'MAR'),
  ('Mexico', 'MEX'),
  ('Netherlands', 'NED'),
  ('Norway', 'NOR'),
  ('New Zealand', 'NZL'),
  ('Panama', 'PAN'),
  ('Paraguay', 'PAR'),
  ('Portugal', 'POR'),
  ('Qatar', 'QAT'),
  ('South Africa', 'RSA'),
  ('Scotland', 'SCO'),
  ('Senegal', 'SEN'),
  ('Switzerland', 'SUI'),
  ('Sweden', 'SWE'),
  ('Tunisia', 'TUN'),
  ('Turkey', 'TUR'),
  ('Uruguay', 'URU'),
  ('USA', 'USA'),
  ('Uzbekistan', 'UZB');

insert into public.partidas (fase, grupo, rodada, data_hora, estadio, status, mandante_id, visitante_id, mandante_label, visitante_label, numero) values
  ('grupos', 'A', 1, '2026-06-11T19:00:00.000Z', 'Mexico City', 'agendada', (select id from selecoes where codigo = 'MEX'), (select id from selecoes where codigo = 'RSA'), null, null, null),
  ('grupos', 'A', 1, '2026-06-12T02:00:00.000Z', 'Guadalajara (Zapopan)', 'agendada', (select id from selecoes where codigo = 'KOR'), (select id from selecoes where codigo = 'CZE'), null, null, null),
  ('grupos', 'A', 8, '2026-06-18T16:00:00.000Z', 'Atlanta', 'agendada', (select id from selecoes where codigo = 'CZE'), (select id from selecoes where codigo = 'RSA'), null, null, null),
  ('grupos', 'A', 8, '2026-06-19T01:00:00.000Z', 'Guadalajara (Zapopan)', 'agendada', (select id from selecoes where codigo = 'MEX'), (select id from selecoes where codigo = 'KOR'), null, null, null),
  ('grupos', 'A', 14, '2026-06-25T01:00:00.000Z', 'Mexico City', 'agendada', (select id from selecoes where codigo = 'CZE'), (select id from selecoes where codigo = 'MEX'), null, null, null),
  ('grupos', 'A', 14, '2026-06-25T01:00:00.000Z', 'Monterrey (Guadalupe)', 'agendada', (select id from selecoes where codigo = 'RSA'), (select id from selecoes where codigo = 'KOR'), null, null, null),
  ('grupos', 'B', 2, '2026-06-12T19:00:00.000Z', 'Toronto', 'agendada', (select id from selecoes where codigo = 'CAN'), (select id from selecoes where codigo = 'BIH'), null, null, null),
  ('grupos', 'B', 3, '2026-06-13T19:00:00.000Z', 'San Francisco Bay Area (Santa Clara)', 'agendada', (select id from selecoes where codigo = 'QAT'), (select id from selecoes where codigo = 'SUI'), null, null, null),
  ('grupos', 'B', 8, '2026-06-18T19:00:00.000Z', 'Los Angeles (Inglewood)', 'agendada', (select id from selecoes where codigo = 'SUI'), (select id from selecoes where codigo = 'BIH'), null, null, null),
  ('grupos', 'B', 8, '2026-06-18T22:00:00.000Z', 'Vancouver', 'agendada', (select id from selecoes where codigo = 'CAN'), (select id from selecoes where codigo = 'QAT'), null, null, null),
  ('grupos', 'B', 14, '2026-06-24T19:00:00.000Z', 'Vancouver', 'agendada', (select id from selecoes where codigo = 'SUI'), (select id from selecoes where codigo = 'CAN'), null, null, null),
  ('grupos', 'B', 14, '2026-06-24T19:00:00.000Z', 'Seattle', 'agendada', (select id from selecoes where codigo = 'BIH'), (select id from selecoes where codigo = 'QAT'), null, null, null),
  ('grupos', 'C', 3, '2026-06-13T22:00:00.000Z', 'New York/New Jersey (East Rutherford)', 'agendada', (select id from selecoes where codigo = 'BRA'), (select id from selecoes where codigo = 'MAR'), null, null, null),
  ('grupos', 'C', 3, '2026-06-14T01:00:00.000Z', 'Boston (Foxborough)', 'agendada', (select id from selecoes where codigo = 'HAI'), (select id from selecoes where codigo = 'SCO'), null, null, null),
  ('grupos', 'C', 9, '2026-06-19T22:00:00.000Z', 'Boston (Foxborough)', 'agendada', (select id from selecoes where codigo = 'SCO'), (select id from selecoes where codigo = 'MAR'), null, null, null),
  ('grupos', 'C', 9, '2026-06-20T00:30:00.000Z', 'Philadelphia', 'agendada', (select id from selecoes where codigo = 'BRA'), (select id from selecoes where codigo = 'HAI'), null, null, null),
  ('grupos', 'C', 14, '2026-06-24T22:00:00.000Z', 'Miami (Miami Gardens)', 'agendada', (select id from selecoes where codigo = 'SCO'), (select id from selecoes where codigo = 'BRA'), null, null, null),
  ('grupos', 'C', 14, '2026-06-24T22:00:00.000Z', 'Atlanta', 'agendada', (select id from selecoes where codigo = 'MAR'), (select id from selecoes where codigo = 'HAI'), null, null, null),
  ('grupos', 'D', 2, '2026-06-13T01:00:00.000Z', 'Los Angeles (Inglewood)', 'agendada', (select id from selecoes where codigo = 'USA'), (select id from selecoes where codigo = 'PAR'), null, null, null),
  ('grupos', 'D', 3, '2026-06-14T04:00:00.000Z', 'Vancouver', 'agendada', (select id from selecoes where codigo = 'AUS'), (select id from selecoes where codigo = 'TUR'), null, null, null),
  ('grupos', 'D', 9, '2026-06-19T19:00:00.000Z', 'Seattle', 'agendada', (select id from selecoes where codigo = 'USA'), (select id from selecoes where codigo = 'AUS'), null, null, null),
  ('grupos', 'D', 9, '2026-06-20T03:00:00.000Z', 'San Francisco Bay Area (Santa Clara)', 'agendada', (select id from selecoes where codigo = 'TUR'), (select id from selecoes where codigo = 'PAR'), null, null, null),
  ('grupos', 'D', 15, '2026-06-26T02:00:00.000Z', 'Los Angeles (Inglewood)', 'agendada', (select id from selecoes where codigo = 'TUR'), (select id from selecoes where codigo = 'USA'), null, null, null),
  ('grupos', 'D', 15, '2026-06-26T02:00:00.000Z', 'San Francisco Bay Area (Santa Clara)', 'agendada', (select id from selecoes where codigo = 'PAR'), (select id from selecoes where codigo = 'AUS'), null, null, null),
  ('grupos', 'E', 4, '2026-06-14T17:00:00.000Z', 'Houston', 'agendada', (select id from selecoes where codigo = 'GER'), (select id from selecoes where codigo = 'CUW'), null, null, null),
  ('grupos', 'E', 4, '2026-06-14T23:00:00.000Z', 'Philadelphia', 'agendada', (select id from selecoes where codigo = 'CIV'), (select id from selecoes where codigo = 'ECU'), null, null, null),
  ('grupos', 'E', 10, '2026-06-20T20:00:00.000Z', 'Toronto', 'agendada', (select id from selecoes where codigo = 'GER'), (select id from selecoes where codigo = 'CIV'), null, null, null),
  ('grupos', 'E', 10, '2026-06-21T00:00:00.000Z', 'Kansas City', 'agendada', (select id from selecoes where codigo = 'ECU'), (select id from selecoes where codigo = 'CUW'), null, null, null),
  ('grupos', 'E', 15, '2026-06-25T20:00:00.000Z', 'Philadelphia', 'agendada', (select id from selecoes where codigo = 'CUW'), (select id from selecoes where codigo = 'CIV'), null, null, null),
  ('grupos', 'E', 15, '2026-06-25T20:00:00.000Z', 'New York/New Jersey (East Rutherford)', 'agendada', (select id from selecoes where codigo = 'ECU'), (select id from selecoes where codigo = 'GER'), null, null, null),
  ('grupos', 'F', 4, '2026-06-14T20:00:00.000Z', 'Dallas (Arlington)', 'agendada', (select id from selecoes where codigo = 'NED'), (select id from selecoes where codigo = 'JPN'), null, null, null),
  ('grupos', 'F', 4, '2026-06-15T02:00:00.000Z', 'Monterrey (Guadalupe)', 'agendada', (select id from selecoes where codigo = 'SWE'), (select id from selecoes where codigo = 'TUN'), null, null, null),
  ('grupos', 'F', 10, '2026-06-20T17:00:00.000Z', 'Houston', 'agendada', (select id from selecoes where codigo = 'NED'), (select id from selecoes where codigo = 'SWE'), null, null, null),
  ('grupos', 'F', 10, '2026-06-21T04:00:00.000Z', 'Monterrey (Guadalupe)', 'agendada', (select id from selecoes where codigo = 'TUN'), (select id from selecoes where codigo = 'JPN'), null, null, null),
  ('grupos', 'F', 15, '2026-06-25T23:00:00.000Z', 'Dallas (Arlington)', 'agendada', (select id from selecoes where codigo = 'JPN'), (select id from selecoes where codigo = 'SWE'), null, null, null),
  ('grupos', 'F', 15, '2026-06-25T23:00:00.000Z', 'Kansas City', 'agendada', (select id from selecoes where codigo = 'TUN'), (select id from selecoes where codigo = 'NED'), null, null, null),
  ('grupos', 'G', 5, '2026-06-15T19:00:00.000Z', 'Seattle', 'agendada', (select id from selecoes where codigo = 'BEL'), (select id from selecoes where codigo = 'EGY'), null, null, null),
  ('grupos', 'G', 5, '2026-06-16T01:00:00.000Z', 'Los Angeles (Inglewood)', 'agendada', (select id from selecoes where codigo = 'IRN'), (select id from selecoes where codigo = 'NZL'), null, null, null),
  ('grupos', 'G', 11, '2026-06-21T19:00:00.000Z', 'Los Angeles (Inglewood)', 'agendada', (select id from selecoes where codigo = 'BEL'), (select id from selecoes where codigo = 'IRN'), null, null, null),
  ('grupos', 'G', 11, '2026-06-22T01:00:00.000Z', 'Vancouver', 'agendada', (select id from selecoes where codigo = 'NZL'), (select id from selecoes where codigo = 'EGY'), null, null, null),
  ('grupos', 'G', 16, '2026-06-27T03:00:00.000Z', 'Seattle', 'agendada', (select id from selecoes where codigo = 'EGY'), (select id from selecoes where codigo = 'IRN'), null, null, null),
  ('grupos', 'G', 16, '2026-06-27T03:00:00.000Z', 'Vancouver', 'agendada', (select id from selecoes where codigo = 'NZL'), (select id from selecoes where codigo = 'BEL'), null, null, null),
  ('grupos', 'H', 5, '2026-06-15T16:00:00.000Z', 'Atlanta', 'agendada', (select id from selecoes where codigo = 'ESP'), (select id from selecoes where codigo = 'CPV'), null, null, null),
  ('grupos', 'H', 5, '2026-06-15T22:00:00.000Z', 'Miami (Miami Gardens)', 'agendada', (select id from selecoes where codigo = 'KSA'), (select id from selecoes where codigo = 'URU'), null, null, null),
  ('grupos', 'H', 11, '2026-06-21T16:00:00.000Z', 'Atlanta', 'agendada', (select id from selecoes where codigo = 'ESP'), (select id from selecoes where codigo = 'KSA'), null, null, null),
  ('grupos', 'H', 11, '2026-06-21T22:00:00.000Z', 'Miami (Miami Gardens)', 'agendada', (select id from selecoes where codigo = 'URU'), (select id from selecoes where codigo = 'CPV'), null, null, null),
  ('grupos', 'H', 16, '2026-06-27T00:00:00.000Z', 'Houston', 'agendada', (select id from selecoes where codigo = 'CPV'), (select id from selecoes where codigo = 'KSA'), null, null, null),
  ('grupos', 'H', 16, '2026-06-27T00:00:00.000Z', 'Guadalajara (Zapopan)', 'agendada', (select id from selecoes where codigo = 'URU'), (select id from selecoes where codigo = 'ESP'), null, null, null),
  ('grupos', 'I', 6, '2026-06-16T19:00:00.000Z', 'New York/New Jersey (East Rutherford)', 'agendada', (select id from selecoes where codigo = 'FRA'), (select id from selecoes where codigo = 'SEN'), null, null, null),
  ('grupos', 'I', 6, '2026-06-16T22:00:00.000Z', 'Boston (Foxborough)', 'agendada', (select id from selecoes where codigo = 'IRQ'), (select id from selecoes where codigo = 'NOR'), null, null, null),
  ('grupos', 'I', 12, '2026-06-22T21:00:00.000Z', 'Philadelphia', 'agendada', (select id from selecoes where codigo = 'FRA'), (select id from selecoes where codigo = 'IRQ'), null, null, null),
  ('grupos', 'I', 12, '2026-06-23T00:00:00.000Z', 'New York/New Jersey (East Rutherford)', 'agendada', (select id from selecoes where codigo = 'NOR'), (select id from selecoes where codigo = 'SEN'), null, null, null),
  ('grupos', 'I', 16, '2026-06-26T19:00:00.000Z', 'Boston (Foxborough)', 'agendada', (select id from selecoes where codigo = 'NOR'), (select id from selecoes where codigo = 'FRA'), null, null, null),
  ('grupos', 'I', 16, '2026-06-26T19:00:00.000Z', 'Toronto', 'agendada', (select id from selecoes where codigo = 'SEN'), (select id from selecoes where codigo = 'IRQ'), null, null, null),
  ('grupos', 'J', 6, '2026-06-17T01:00:00.000Z', 'Kansas City', 'agendada', (select id from selecoes where codigo = 'ARG'), (select id from selecoes where codigo = 'ALG'), null, null, null),
  ('grupos', 'J', 6, '2026-06-17T04:00:00.000Z', 'San Francisco Bay Area (Santa Clara)', 'agendada', (select id from selecoes where codigo = 'AUT'), (select id from selecoes where codigo = 'JOR'), null, null, null),
  ('grupos', 'J', 12, '2026-06-22T17:00:00.000Z', 'Dallas (Arlington)', 'agendada', (select id from selecoes where codigo = 'ARG'), (select id from selecoes where codigo = 'AUT'), null, null, null),
  ('grupos', 'J', 12, '2026-06-23T03:00:00.000Z', 'San Francisco Bay Area (Santa Clara)', 'agendada', (select id from selecoes where codigo = 'JOR'), (select id from selecoes where codigo = 'ALG'), null, null, null),
  ('grupos', 'J', 17, '2026-06-28T02:00:00.000Z', 'Kansas City', 'agendada', (select id from selecoes where codigo = 'ALG'), (select id from selecoes where codigo = 'AUT'), null, null, null),
  ('grupos', 'J', 17, '2026-06-28T02:00:00.000Z', 'Dallas (Arlington)', 'agendada', (select id from selecoes where codigo = 'JOR'), (select id from selecoes where codigo = 'ARG'), null, null, null),
  ('grupos', 'K', 7, '2026-06-17T17:00:00.000Z', 'Houston', 'agendada', (select id from selecoes where codigo = 'POR'), (select id from selecoes where codigo = 'COD'), null, null, null),
  ('grupos', 'K', 7, '2026-06-18T02:00:00.000Z', 'Mexico City', 'agendada', (select id from selecoes where codigo = 'UZB'), (select id from selecoes where codigo = 'COL'), null, null, null),
  ('grupos', 'K', 13, '2026-06-23T17:00:00.000Z', 'Houston', 'agendada', (select id from selecoes where codigo = 'POR'), (select id from selecoes where codigo = 'UZB'), null, null, null),
  ('grupos', 'K', 13, '2026-06-24T02:00:00.000Z', 'Guadalajara (Zapopan)', 'agendada', (select id from selecoes where codigo = 'COL'), (select id from selecoes where codigo = 'COD'), null, null, null),
  ('grupos', 'K', 17, '2026-06-27T23:30:00.000Z', 'Miami (Miami Gardens)', 'agendada', (select id from selecoes where codigo = 'COL'), (select id from selecoes where codigo = 'POR'), null, null, null),
  ('grupos', 'K', 17, '2026-06-27T23:30:00.000Z', 'Atlanta', 'agendada', (select id from selecoes where codigo = 'COD'), (select id from selecoes where codigo = 'UZB'), null, null, null),
  ('grupos', 'L', 7, '2026-06-17T20:00:00.000Z', 'Dallas (Arlington)', 'agendada', (select id from selecoes where codigo = 'ENG'), (select id from selecoes where codigo = 'CRO'), null, null, null),
  ('grupos', 'L', 7, '2026-06-17T23:00:00.000Z', 'Toronto', 'agendada', (select id from selecoes where codigo = 'GHA'), (select id from selecoes where codigo = 'PAN'), null, null, null),
  ('grupos', 'L', 13, '2026-06-23T20:00:00.000Z', 'Boston (Foxborough)', 'agendada', (select id from selecoes where codigo = 'ENG'), (select id from selecoes where codigo = 'GHA'), null, null, null),
  ('grupos', 'L', 13, '2026-06-23T23:00:00.000Z', 'Toronto', 'agendada', (select id from selecoes where codigo = 'PAN'), (select id from selecoes where codigo = 'CRO'), null, null, null),
  ('grupos', 'L', 17, '2026-06-27T21:00:00.000Z', 'New York/New Jersey (East Rutherford)', 'agendada', (select id from selecoes where codigo = 'PAN'), (select id from selecoes where codigo = 'ENG'), null, null, null),
  ('grupos', 'L', 17, '2026-06-27T21:00:00.000Z', 'Philadelphia', 'agendada', (select id from selecoes where codigo = 'CRO'), (select id from selecoes where codigo = 'GHA'), null, null, null),
  ('trinta-e-dois', null, 18, '2026-06-28T19:00:00.000Z', 'Los Angeles (Inglewood)', 'agendada', (select id from selecoes where codigo = 'RSA'), (select id from selecoes where codigo = 'CAN'), null, null, 73),
  ('trinta-e-dois', null, 18, '2026-06-29T20:30:00.000Z', 'Boston (Foxborough)', 'agendada', (select id from selecoes where codigo = 'GER'), (select id from selecoes where codigo = 'PAR'), null, null, 74),
  ('trinta-e-dois', null, 18, '2026-06-30T01:00:00.000Z', 'Monterrey (Guadalupe)', 'agendada', (select id from selecoes where codigo = 'NED'), (select id from selecoes where codigo = 'MAR'), null, null, 75),
  ('trinta-e-dois', null, 18, '2026-06-29T17:00:00.000Z', 'Houston', 'agendada', (select id from selecoes where codigo = 'BRA'), (select id from selecoes where codigo = 'JPN'), null, null, 76),
  ('trinta-e-dois', null, 18, '2026-06-30T21:00:00.000Z', 'New York/New Jersey (East Rutherford)', 'agendada', (select id from selecoes where codigo = 'FRA'), (select id from selecoes where codigo = 'SWE'), null, null, 77),
  ('trinta-e-dois', null, 18, '2026-06-30T17:00:00.000Z', 'Dallas (Arlington)', 'agendada', (select id from selecoes where codigo = 'CIV'), (select id from selecoes where codigo = 'NOR'), null, null, 78),
  ('trinta-e-dois', null, 18, '2026-07-01T01:00:00.000Z', 'Mexico City', 'agendada', (select id from selecoes where codigo = 'MEX'), (select id from selecoes where codigo = 'ECU'), null, null, 79),
  ('trinta-e-dois', null, 18, '2026-07-01T16:00:00.000Z', 'Atlanta', 'agendada', (select id from selecoes where codigo = 'ENG'), (select id from selecoes where codigo = 'COD'), null, null, 80),
  ('trinta-e-dois', null, 18, '2026-07-02T00:00:00.000Z', 'San Francisco Bay Area (Santa Clara)', 'agendada', (select id from selecoes where codigo = 'USA'), (select id from selecoes where codigo = 'BIH'), null, null, 81),
  ('trinta-e-dois', null, 18, '2026-07-01T20:00:00.000Z', 'Seattle', 'agendada', (select id from selecoes where codigo = 'BEL'), (select id from selecoes where codigo = 'SEN'), null, null, 82),
  ('trinta-e-dois', null, 18, '2026-07-02T23:00:00.000Z', 'Toronto', 'agendada', (select id from selecoes where codigo = 'POR'), (select id from selecoes where codigo = 'CRO'), null, null, 83),
  ('trinta-e-dois', null, 18, '2026-07-02T19:00:00.000Z', 'Los Angeles (Inglewood)', 'agendada', (select id from selecoes where codigo = 'ESP'), (select id from selecoes where codigo = 'AUT'), null, null, 84),
  ('trinta-e-dois', null, 18, '2026-07-03T03:00:00.000Z', 'Vancouver', 'agendada', (select id from selecoes where codigo = 'SUI'), (select id from selecoes where codigo = 'ALG'), null, null, 85),
  ('trinta-e-dois', null, 18, '2026-07-03T22:00:00.000Z', 'Miami (Miami Gardens)', 'agendada', (select id from selecoes where codigo = 'ARG'), (select id from selecoes where codigo = 'CPV'), null, null, 86),
  ('trinta-e-dois', null, 18, '2026-07-04T01:30:00.000Z', 'Kansas City', 'agendada', (select id from selecoes where codigo = 'COL'), (select id from selecoes where codigo = 'GHA'), null, null, 87),
  ('trinta-e-dois', null, 18, '2026-07-03T18:00:00.000Z', 'Dallas (Arlington)', 'agendada', (select id from selecoes where codigo = 'AUS'), (select id from selecoes where codigo = 'EGY'), null, null, 88),
  ('oitavas', null, 19, '2026-07-04T21:00:00.000Z', 'Philadelphia', 'agendada', null, null, 'W74', 'W77', 89),
  ('oitavas', null, 19, '2026-07-04T17:00:00.000Z', 'Houston', 'agendada', (select id from selecoes where codigo = 'CAN'), null, null, 'W75', 90),
  ('oitavas', null, 19, '2026-07-05T20:00:00.000Z', 'New York/New Jersey (East Rutherford)', 'agendada', null, null, 'W76', 'W78', 91),
  ('oitavas', null, 19, '2026-07-06T00:00:00.000Z', 'Mexico City', 'agendada', null, null, 'W79', 'W80', 92),
  ('oitavas', null, 19, '2026-07-06T19:00:00.000Z', 'Dallas (Arlington)', 'agendada', null, null, 'W83', 'W84', 93),
  ('oitavas', null, 19, '2026-07-07T00:00:00.000Z', 'Seattle', 'agendada', null, null, 'W81', 'W82', 94),
  ('oitavas', null, 19, '2026-07-07T16:00:00.000Z', 'Atlanta', 'agendada', null, null, 'W86', 'W88', 95),
  ('oitavas', null, 19, '2026-07-07T20:00:00.000Z', 'Vancouver', 'agendada', null, null, 'W85', 'W87', 96),
  ('quartas', null, 20, '2026-07-09T20:00:00.000Z', 'Boston (Foxborough)', 'agendada', null, null, 'W89', 'W90', 97),
  ('quartas', null, 20, '2026-07-10T19:00:00.000Z', 'Los Angeles (Inglewood)', 'agendada', null, null, 'W93', 'W94', 98),
  ('quartas', null, 20, '2026-07-11T21:00:00.000Z', 'Miami (Miami Gardens)', 'agendada', null, null, 'W91', 'W92', 99),
  ('quartas', null, 20, '2026-07-12T01:00:00.000Z', 'Kansas City', 'agendada', null, null, 'W95', 'W96', 100),
  ('semifinal', null, 21, '2026-07-14T19:00:00.000Z', 'Dallas (Arlington)', 'agendada', null, null, 'W97', 'W98', 101),
  ('semifinal', null, 21, '2026-07-15T19:00:00.000Z', 'Atlanta', 'agendada', null, null, 'W99', 'W100', 102),
  ('terceiro-lugar', null, 22, '2026-07-18T21:00:00.000Z', 'Miami (Miami Gardens)', 'agendada', null, null, 'L101', 'L102', 103),
  ('final', null, 23, '2026-07-19T19:00:00.000Z', 'New York/New Jersey (East Rutherford)', 'agendada', null, null, 'W101', 'W102', 104);
