/** Nome da seleção (como vem do openfootball) → código FIFA de 3 letras. */
export const FIFA_CODES: Record<string, string> = {
  Mexico: "MEX",
  "South Africa": "RSA",
  "South Korea": "KOR",
  "Czech Republic": "CZE",
  Canada: "CAN",
  USA: "USA",
  Brazil: "BRA",
  Argentina: "ARG",
  France: "FRA",
  England: "ENG",
  Spain: "ESP",
  Germany: "GER",
  Portugal: "POR",
  Netherlands: "NED",
  Belgium: "BEL",
  Croatia: "CRO",
  Uruguay: "URU",
  Colombia: "COL",
  Ecuador: "ECU",
  Paraguay: "PAR",
  Morocco: "MAR",
  Senegal: "SEN",
  Egypt: "EGY",
  Algeria: "ALG",
  Tunisia: "TUN",
  Ghana: "GHA",
  "Ivory Coast": "CIV",
  "Cape Verde": "CPV",
  "DR Congo": "COD",
  Japan: "JPN",
  Iran: "IRN",
  Iraq: "IRQ",
  "Saudi Arabia": "KSA",
  Qatar: "QAT",
  Jordan: "JOR",
  Uzbekistan: "UZB",
  Australia: "AUS",
  "New Zealand": "NZL",
  Switzerland: "SUI",
  Austria: "AUT",
  Norway: "NOR",
  Sweden: "SWE",
  Scotland: "SCO",
  Turkey: "TUR",
  Panama: "PAN",
  Haiti: "HAI",
  Curaçao: "CUW",
  "Bosnia & Herzegovina": "BIH",
};
